###################################################################################
#         ___  ____    __    _  _  ____     ____  _   _  ____  ____  ____         #
#        / __)(  _ \  /__\  ( \( )(  _ \   (_  _)( )_( )( ___)( ___)(_  _)        #
#       ( (_-. )   / /(__)\  )  (  )(_) )    )(   ) _ (  )__)  )__)   )(          #  
#        \___/(_)\_)(__)(__)(_)\_)(____/    (__) (_) (_)(____)(__)   (__)         # 
#               __  __  ____  _  _  ____  ___    __    ____  ____                 #
#              (  \/  )(_  _)( \( )( ___)/ __)  /__\  (  _ \(_  _)                #
#               )    (  _)(_  )  (  )__)( (__  /(__)\  )   /  )(                  #  
#              (_/\/\_)(____)(_)\_)(____)\___)(__)(__)(_)\_) (__)                 #
#                                                                                 #
###################################################################################

InformAboutUpdates: true
WantedLevel:
  Condition:
    AttackMob: 0
    KillMob: 0
    AttackPlayer: 0
    KillPlayer: 1
    AttackPolice: 2
    KillPolice: 3
  Time:
    # Time in seconds a player have to hide from the police to lose his WantedLevel
    OneStar: 40
    TwoStars: 60
    ThreeStarts: 80
    FourStars: 100
    FiveStars: 120
  Spawn:
    # Amount of Police spwaned per level
    OneStar: 
      Officers: 2
      Snipers: 0
      Swats: 0
    TwoStars: 
      Officers: 4
      Snipers: 0
      Swats: 0
    ThreeStarts: 
      Officers: 6
      Snipers: 3
      Swats: 0
    FourStars: 
      Officers: 0
      Snipers: 2
      Swats: 4
    FiveStars: 
      Officers: 0
      Snipers: 4
      Swats: 8
# If set to true, mob name will be constantly visible.
MobNameVisible: false
Police:
  Officer:
    Name: Police Officer
    Equipment:
      Helmet: AIR
      Chestplate: LEATHER_CHESTPLATE
      Leggings: AIR
      Boots: AIR
      Weapon: AIR
  Sniper:
    Name: Sniper
    Equipment:
      Helmet: AIR
      Chestplate: LEATHER_CHESTPLATE
      Leggings: AIR
      Boots: AIR
  Swat:
    Name: SWAT
    Equipment:
      Helmet: IRON_HELMET
      Chestplate: LEATHER_CHESTPLATE
      Leggings: LEATHER_LEGGINGS
      Boots: AIR
      Weapon: IRON_SWORD