name: GrandTheftMinecart
main: me.ToastHelmi.GrandTheftMinecart.GrandTheftMinecart
version: ${version}
author: ToastHelmi
description: add GTA-Features to Minecraft
commands:
  GTM:
    description: The base GrandTheftMinecart command.