name: GrandTheftMinecart
main: me.ToastHelmi.GrandTheftMinecart.GrandTheftMinecart
version: 2.0.1
author: ToastHelmi
description: add GTA-Features to Minecraft
commands:
  GTM:
    description: The base GrandTheftMinecart command.